services:
  postgres:
    image: postgres:16-alpine
    container_name: tp-postgres
    restart: always
    environment:
      POSTGRES_DB: trip_planner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootp4ssworD
    ports:
      - "5432:5432"
    volumes:
      - tp-pg-data:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb:latest
    container_name: pgweb
    restart: always
    ports:
      - "8081:8081"
    links:
      - postgres:tp-postgres
    environment:
      PGWEB_DATABASE_URL: postgres://postgres:rootp4ssworD@postgres:5432/trip_planner?sslmode=disable
    depends_on:
      - postgres

volumes:
  tp-pg-data:
