services:
  postgres:
    image: postgres:16-alpine
    container_name: tp-postgres
    restart: always
    environment:
      POSTGRES_DB: trip_planner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootp4ssworD
    ports:
      - "5432:5432"
    volumes:
      - tp-pg-data:/var/lib/postgresql/data

volumes:
  tp-pg-data:
